---
- hosts: dbserver
  vars:
  - warName: LoginWebApp1.war
  - tomcat_version: 10.1.8
  - warRemotePath: /opt/tomcat10/webapps

  tasks:
  - name: Copy WAR to Remote server
    copy: src=/tmp/target/LoginWebApp-1.war dest=/opt/tomcat10/webapps/  owner=tomcat group=tomcat
